### ISSUE TITLE
Support negotiating HTTP/2 with example server

### ISSUE THREAD

**Issue by johnthuss** [apple/swift-nio-http2#70]
The example server at "Sources/NIOHTTP2Server/main.swift" can currently only be communicated with using a specific curl command line, not a web browser. In order for a community to begin experimenting with this project there needs to be an example that communicate with a web browser out of the box.

`curl --http2-prior-knowledge`

**Comment by Lukasa** [comment]
This example is out-of-scope for this repository because it creates a hard dependency on swift-nio-ssl, which is the only way to negotiate with a browser. It's an annoying limitation, but it's the current state of play.

As recently discussed on the [Swift forums](https://forums.swift.org/t/swift-nio-http-2-negotiation/21982), it would be profoundly useful to have such an example, but it cannot live in this respository.

**Comment by MrMage** [comment]
I think SSL should not be needed for negotiating an upgrade from (**non-encrypted**) HTTP1 to HTTP2. See https://github.com/grpc/grpc-swift/blob/nio/Sources/SwiftGRPCNIO/HTTPProtocolSwitcher.swift for an example.

**Comment by Lukasa** [comment]
@MrMage While that's true, @johnthuss' request was "there needs to be an example that communicate with a web browser out of the box", and no browser performs plaintext upgrade.

**Comment by MrMage** [comment]
@Lukasa thanks for the elaboration! I was not aware of that.
